"""initial_schema — todas las tablas del dominio FoodStore.

Generada con `alembic revision --autogenerate` (SQLite vacío); las columnas `id`
llevan `autoincrement=True` para que PostgreSQL cree secuencias/identity correctas.

Revision ID: 0c653a5230b5
Revises:
Create Date: 2026-04-10 10:33:52.941587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c653a5230b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'nombre', name='uq_categorias_parent_nombre')
    )
    op.create_index(op.f('ix_categorias_parent_id'), 'categorias', ['parent_id'], unique=False)
    op.create_table('estados_pedido',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('forma_pago',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('habilitado', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('es_alergeno', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('direcciones_entrega',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('linea1', sa.Text(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_entrega_usuario_id'), 'direcciones_entrega', ['usuario_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('imagen_url', sa.String(length=2048), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stock_cantidad >= 0', name='ck_productos_stock_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_productos_sku')
    )
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_origen', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_codigo', sa.String(length=20), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rol_codigo'], ['roles.codigo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_codigo', name='uq_usuario_rol_usuario_rol')
    )
    op.create_index(op.f('ix_usuario_rol_rol_codigo'), 'usuario_rol', ['rol_codigo'], unique=False)
    op.create_index(op.f('ix_usuario_rol_usuario_id'), 'usuario_rol', ['usuario_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion_entrega_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'EN_PREP', 'EN_CAMINO', 'ENTREGADO', 'CANCELADO', name='estado_pedido', native_enum=False), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('estado_codigo', sa.String(length=20), server_default='PENDIENTE', nullable=False),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('observaciones_cliente', sa.String(length=500), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['direccion_entrega_id'], ['direcciones_entrega.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_pedido.codigo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_direccion_entrega_id'), 'pedidos', ['direccion_entrega_id'], unique=False)
    op.create_index(op.f('ix_pedidos_estado_codigo'), 'pedidos', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_table('producto_ingrediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('es_removible', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_producto_ingrediente_cantidad_positiva'),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'ingrediente_id', name='uq_producto_ingrediente_producto_ingrediente')
    )
    op.create_index(op.f('ix_producto_ingrediente_ingrediente_id'), 'producto_ingrediente', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_producto_ingrediente_producto_id'), 'producto_ingrediente', ['producto_id'], unique=False)
    op.create_table('detalle_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_producto', sa.String(length=200), nullable=False),
    sa.Column('precio_unitario_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('personalizacion', sa.JSON(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='ck_detalle_pedido_cantidad_positiva'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_pedido_pedido_id'), 'detalle_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_producto_id'), 'detalle_pedido', ['producto_id'], unique=False)
    op.create_table('historial_estado_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=32), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=32), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estado_pedido_pedido_id'), 'historial_estado_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_historial_estado_pedido_usuario_id'), 'historial_estado_pedido', ['usuario_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('forma_pago_codigo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'APROBADO', 'RECHAZADO', 'REEMBOLSADO', name='estado_pago', native_enum=False), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('external_reference', sa.String(length=64), nullable=False),
    sa.Column('mp_payment_id', sa.String(length=64), nullable=True),
    sa.Column('mp_status', sa.String(length=32), nullable=True),
    sa.Column('proveedor_referencia_id', sa.String(length=128), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['forma_pago.codigo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_pagos_idempotency_key')
    )
    op.create_index(op.f('ix_pagos_external_reference'), 'pagos', ['external_reference'], unique=False)
    op.create_index(op.f('ix_pagos_forma_pago_codigo'), 'pagos', ['forma_pago_codigo'], unique=False)
    op.create_index(op.f('ix_pagos_mp_payment_id'), 'pagos', ['mp_payment_id'], unique=False)
    op.create_index(op.f('ix_pagos_pedido_id'), 'pagos', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pagos_proveedor_referencia_id'), 'pagos', ['proveedor_referencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_proveedor_referencia_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_pedido_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_mp_payment_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_forma_pago_codigo'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_external_reference'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_historial_estado_pedido_usuario_id'), table_name='historial_estado_pedido')
    op.drop_index(op.f('ix_historial_estado_pedido_pedido_id'), table_name='historial_estado_pedido')
    op.drop_table('historial_estado_pedido')
    op.drop_index(op.f('ix_detalle_pedido_producto_id'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_detalle_pedido_pedido_id'), table_name='detalle_pedido')
    op.drop_table('detalle_pedido')
    op.drop_index(op.f('ix_producto_ingrediente_producto_id'), table_name='producto_ingrediente')
    op.drop_index(op.f('ix_producto_ingrediente_ingrediente_id'), table_name='producto_ingrediente')
    op.drop_table('producto_ingrediente')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado_codigo'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_direccion_entrega_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_usuario_rol_usuario_id'), table_name='usuario_rol')
    op.drop_index(op.f('ix_usuario_rol_rol_codigo'), table_name='usuario_rol')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_direcciones_entrega_usuario_id'), table_name='direcciones_entrega')
    op.drop_table('direcciones_entrega')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('ingredientes')
    op.drop_table('forma_pago')
    op.drop_table('estados_pedido')
    op.drop_index(op.f('ix_categorias_parent_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
